<?php
if(!empty($errorMessage)){
    echo "<script>alert('{$errorMessage}')</script>";
}
?>
<div class="row h-100">
    <div class="col-12 dark-bg">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-6 p-md-5">
                    <div class="text-center py-5">
                        <img src="<?=ABSPATH?>/img/logo.png" />
                    </div>
                    <div class="text-center mb-3">
                        <h2 class="text-white">INICIA SESION</h2>
                    </div>
                    <form method="post">
                        <div class="mb-3">
                            <input value="<?=$email?>" required type="email" class="form-control" id="email" name="email" placeholder="Email" />
                        </div>
                        <div class="mb-3">
                            <input required type="password" class="form-control" id="password" name="password" placeholder="Contraseña" />
                        </div>
                        <div class="mb-3 text-center">
                            <button type="submit" class="btn btn-primary btn-lg">GUARDAR</button>
                        </div>
                        <div class="mb-3 text-center text-white">
                            ¿Aún no tienes cuenta? <a class="fw-bold text-decoration-none text-white" href="<?=ABSPATH?>/user/register">Regístrate</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>