<?php

if (!empty($errorMessage)) {
    echo "<script>alert('{$errorMessage}')</script>";
}
?>
<div class="row h-100">
    <div class="col-12 dark-bg">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-6 m-md-5 bg-white rounded-3">
                    <div class="text-center py-5">
                        <img src="<?=ABSPATH?>/img/logo.png"/>
                    </div>
                    <div class="text-center mb-3">
                        <h2>REGÍSTRATE</h2>
                    </div>
                    <form method="post">
                        <div class="mb-3">
                            <input value="<?=$name?>" required type="text" class="form-control" id="name" name="name" placeholder="Nombres"/>
                        </div>
                        <div class="mb-3">
                            <input value="<?=$email?>" required type="email" class="form-control" id="email" name="email" placeholder="Email"/>
                        </div>
                        <div class="mb-3">
                            <input required type="password" class="form-control" id="password" name="password" placeholder="Contraseña"/>
                        </div>
                        <div class="mb-3 text-center">
                            <button type="submit" class="btn btn-primary btn-lg">GUARDAR</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>