<div class="row">
    <div class="col-12 dark-bg">
        <div class="float-start">
            <img src="<?=ABSPATH?>/img/logo2.png" />
        </div>
        <div class="float-end py-3">
            <a class="btn btn-primary" title="Cerrar Sesión" href="<?=ABSPATH?>/user/logout">
                <i class="bi bi-box-arrow-left"></i>
            </a>
        </div>
    </div>
    <div class="col-12">
        <div class="my-4">
            <h2 class="text-decoration-underline text-center">
                DASHBOARD
            </h2>
        </div>
    </div>
    <div class="col-12">
        <div class="container">
            <div class="row gx-5">
                <div class="col-12 col-md-6">
                    <div class="rounded-3 border bg-white p-3">
                        <h4 class="text-center">
                            Aprobar Usuarios
                        </h4>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr class="table-dark">
                                        <th>Nombre</th>
                                        <th>Email</th>
                                        <th>Acción</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($users as $user): ?>
                                        <tr>
                                            <td><?=$user->name?></td>
                                            <td><?=$user->email?></td>
                                            <td>
                                                <button class="btn btn-primary btn-sm" onclick="if(confirm('Desea Aceptar este Usuario?'))enableUser('<?=$user->id?>',1)">Aceptar</button>
                                                &nbsp;
                                                <button class="btn btn-danger btn-sm" onclick="if(confirm('Desea Rechazar este Usuario?'))enableUser('<?=$user->id?>',0)">Rechazar</button>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-6">
                    <div class="rounded-3 border bg-white p-3">
                        <h4 class="text-center">
                            Noticias
                        </h4>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr class="table-dark">
                                        <th>Título</th>
                                        <th>Acción</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($news as $new): ?>
                                    <tr>
                                        <td><?=$new->title?></td>
                                        <td>
                                            <button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#newsModal" data-bs-id="<?=$new->id?>">Ver más</button>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row gx-5">
                <div class="col-12 mt-5">
                    <div class="rounded-3 border bg-white p-3">
                        <h4 class="text-center">
                            Crear Noticias
                        </h4>
                        <form method="post" enctype="multipart/form-data">
                            <div class="row">
                                <div class="col-12 col-md-6 p-3">
                                    <input value="<?=$title?>" required type="text" class="form-control" id="title" name="title" placeholder="Título"/>
                                </div>
                                <div class="col-12 col-md-6 p-3">
                                    <input value="<?=$press?>" required type="text" class="form-control" id="press" name="press" placeholder="Medio"/>
                                </div>
                                <div class="col-12 col-md-6 p-3">
                                    <input value="<?=$date?>" required type="date" class="form-control" id="date" name="date" placeholder="Fecha"/>
                                </div>
                                <div class="col-12 col-md-6 p-3">
                                    <input type="file" class="form-control" id="file" name="file" multiple="false"/>
                                </div>
                                <div class="col-12 p-3 text-center">
                                    <button type="submit" class="btn btn-primary btn-sm">GUARDAR</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="newsModal" tabindex="-1" aria-labelledby="newsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newsModalLabel">Noticia</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-12 col-md-6">
                        Título:
                    </div>
                    <div class="col-12 col-md-6">
                        <span id="newsTitle"></span>
                    </div>
                    <div class="col-12 col-md-6">
                        Medio:
                    </div>
                    <div class="col-12 col-md-6">
                        <span id="newsPress" class="fw-bold"></span>
                    </div>
                    <div class="col-12 col-md-6">
                        Fecha:
                    </div>
                    <div class="col-12 col-md-6">
                        <span id="newsDate"></span>
                    </div>
                    <div class="col-12">
                        <img id="newsFile" class="img-fluid img-thumbnail"/>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var exampleModal = document.getElementById('newsModal');
    exampleModal.addEventListener('show.bs.modal', function (event) {
        // Button that triggered the modal
        var button = event.relatedTarget;
        // Extract info from data-bs-* attributes
        var id = button.getAttribute('data-bs-id');
        viewMore(id);
    })
    function viewMore(id){
        $.ajax("<?=ABSPATH?>/index/news/"+id,{
            dataType: 'json'
        }).done(function(data){
            $("#newsTitle").html(data.title);
            $("#newsPress").html(data.press);
            $("#newsDate").html(data.date);
            $("#newsFile").attr("src",data.file);
        })
    }
    function enableUser(id,action){
        $.ajax("<?=ABSPATH?>/user/enable/"+id,{
            dataType: 'json',
            type: 'post',
            data: {
                action: action
            }
        }).done(function(data){
            alert(data.message);
        })
    }
</script>